"""設定定数"""

# 予測開放に必要な最小日数
MIN_DAYS_TODAY = 14
MIN_DAYS_3D = 60
MIN_UNHEALTHY_3D = 10

# LightGBM切替条件
LGBM_MIN_DAYS = 60
LGBM_MIN_UNHEALTHY = 10

# 検証用：直近14日をテストセットとして使用
VALIDATION_DAYS = 14

# 信頼度ルール
CONFIDENCE_HIGH_DAYS = 60
CONFIDENCE_HIGH_UNHEALTHY = 10
CONFIDENCE_MEDIUM_DAYS = 30
CONFIDENCE_MEDIUM_UNHEALTHY = 5

# 欠損率による信頼度ダウングレード閾値
MISSING_RATE_THRESHOLD = 0.3

# バッチ対象：直近N日以内に更新があったユーザー
ACTIVE_USER_DAYS = 2
