"""設定定数"""

# 予測開放に必要な最小日数
MIN_DAYS_TODAY = 14
MIN_DAYS_3D = 60
MIN_UNHEALTHY_3D = 10

# LightGBM切替条件
LGBM_MIN_DAYS = 60
LGBM_MIN_UNHEALTHY = 10
MODEL_SELECTION_MAX_STD = 0.1  # 1σルールのσ上限（CV分散が大きい時にLGBMを過度に不利にしない）

# TSCV設定（Expanding Window）
TSCV_FOLDS_SMALL = 2    # 14-29日
TSCV_FOLDS_MEDIUM = 3   # 30-99日
TSCV_FOLDS_LARGE = 5    # 100日以上
TSCV_TEST_DAYS_MEDIUM = 7
TSCV_TEST_DAYS_LARGE = 14
TSCV_MIN_TEST_POSITIVES = 2  # テスト正例がこの数未満のfoldはスキップ

# 信頼度ルール
CONFIDENCE_HIGH_DAYS = 60
CONFIDENCE_HIGH_UNHEALTHY = 10
CONFIDENCE_MEDIUM_DAYS = 30
CONFIDENCE_MEDIUM_UNHEALTHY = 5

# 欠損率による信頼度ダウングレード閾値
MISSING_RATE_THRESHOLD = 0.3

# バッチ対象：直近N日以内に更新があったユーザー
ACTIVE_USER_DAYS = 2
