// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASXhVfS4kRl-L35e-DhCZm7pVn6GDwDYI',
    appId: '1:480274101583:web:6389fa77682b1f799e813a',
    messagingSenderId: '480274101583',
    projectId: 'health-predictor-601e9',
    authDomain: 'health-predictor-601e9.firebaseapp.com',
    storageBucket: 'health-predictor-601e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoJisLbT7GBZPEgVCcyYQwW3XJQbs0bY0',
    appId: '1:480274101583:android:9db6af10921561f59e813a',
    messagingSenderId: '480274101583',
    projectId: 'health-predictor-601e9',
    storageBucket: 'health-predictor-601e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdbP38PN4ggzlEXZOFoQnzlLbg2_VhCtQ',
    appId: '1:480274101583:ios:dee819a1b9e068149e813a',
    messagingSenderId: '480274101583',
    projectId: 'health-predictor-601e9',
    storageBucket: 'health-predictor-601e9.firebasestorage.app',
    iosBundleId: 'com.example.healthPredictor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdbP38PN4ggzlEXZOFoQnzlLbg2_VhCtQ',
    appId: '1:480274101583:ios:dee819a1b9e068149e813a',
    messagingSenderId: '480274101583',
    projectId: 'health-predictor-601e9',
    storageBucket: 'health-predictor-601e9.firebasestorage.app',
    iosBundleId: 'com.example.healthPredictor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASXhVfS4kRl-L35e-DhCZm7pVn6GDwDYI',
    appId: '1:480274101583:web:5f7573e2dc3dda179e813a',
    messagingSenderId: '480274101583',
    projectId: 'health-predictor-601e9',
    authDomain: 'health-predictor-601e9.firebaseapp.com',
    storageBucket: 'health-predictor-601e9.firebasestorage.app',
  );
}
